### ISSUE TITLE
Add a check for the ability to get the phone number

### ISSUE THREAD

**Issue by ammaratef45** [amorenew/Flutter-Mobile-Number-Plugin#1]
I Think you may add a check for the ability to get the phone number (like if it's an iOS app)
For example instead of this:
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/64424e28e115a0e24c445fed031fd193541382bf/example/lib/main.dart#L27-L31

The code can look like this
```
if(await MobileNumber.canGetNumber) {
  try {
      mobileNumber = await MobileNumber.mobileNumber;
    } on Exception{
            mobileNumber = 'Failed to get mobile number.';
    }
} else {
  mobileNumber = 'auto detecting number isn't supported';
}

```

**Comment by amorenew** [comment]
Ok I will update it thanks

**Comment by amorenew** [comment]
canGetNumber could be same as mobile  number is empty
there is no direct check so we have to call get mobile number anyway

The error on the console will look like this message
```
on PlatformException catch (e) {
      debugPrint("Failed to get mobile number because of '${e.message}'");
    }

```
`05:07:28.652 54 info flutter.tools I/flutter (27079): Failed to get mobile number because of 'No phone number on sim card'
`

**Comment by Sahil255** [comment]
null value returned!

**Comment by amorenew** [comment]
@Sahil255 if the value is empty or null that's mean the sim card not allow to return the registered number
